name: focus_timer
description: "A Pomodoro Focus Timer app for productivity"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  
  # Utils
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1
  injectable_generator: ^2.4.2

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/sounds/
    - assets/icons/
